const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.custom,
		C3.Plugins.Timeline,
		C3.Behaviors.MoveTo,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Timeline.Acts.PlayAllTimelines,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Plugins.Timeline.Cnds.OnAnyTimelineFinished,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{BackgroundTile: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Solid: 0},
	{SolidTile: 0},
	{Sine: 0},
	{MovingSolidTile: 0},
	{Jumpthru: 0},
	{JumpThruTile: 0},
	{Keyboard: 0},
	{Text: 0},
	{音頻: 0},
	{平臺: 0},
	{自定義移動: 0},
	{精靈: 0},
	{時間軸: 0},
	{移動到: 0},
	{精靈2: 0},
	{精靈3: 0},
	{實體: 0},
	{精靈4: 0},
	{精靈5: 0},
	{精靈6: 0}
];

self.InstanceType = {
	BackgroundTile: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	SolidTile: class extends self.ITiledBackgroundInstance {},
	MovingSolidTile: class extends self.ITiledBackgroundInstance {},
	JumpThruTile: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	音頻: class extends self.IInstance {},
	精靈: class extends self.ISpriteInstance {},
	時間軸: class extends self.IInstance {},
	精靈2: class extends self.ISpriteInstance {},
	精靈3: class extends self.ISpriteInstance {},
	精靈4: class extends self.ISpriteInstance {},
	精靈5: class extends self.ISpriteInstance {},
	精靈6: class extends self.ISpriteInstance {}
}